"""Register map and Home Assistant sensor descriptions."""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    EntityCategory,
    UnitOfApparentPower,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfPower,
    UnitOfReactiveEnergy,
    UnitOfReactivePower,
)

from .const import (
    CT_PRIMARY_2_ADDRESS,
    CT_PRIMARY_ADDRESS,
    DMD_INTEGRATION_ADDRESS,
    EC_MODE_ADDRESS,
    KWH_PER_PULSE_OUT1_ADDRESS,
    KWH_PER_PULSE_OUT2_ADDRESS,
    LOCK_STATUS_ADDRESS,
    MEASURING_SYSTEM_ADDRESS,
    PRODUCTION_YEAR_ADDRESS,
    RS485_ADDRESS_ADDRESS,
    RS485_BAUD_ADDRESS,
    RS485_PARITY_ADDRESS,
    SECONDARY_ADDRESS_START,
    SUM_VIRTUAL_ADDRESS,
    TCD_PHASE_ORDER_A1_ADDRESS,
    TCD_PHASE_ORDER_A2_ADDRESS,
    TON_TIME_ADDRESS,
    VT_RATIO_ADDRESS,
)


@dataclass(frozen=True, kw_only=True)
class RegisterSensorDescription(SensorEntityDescription):
    """Description of a register-backed sensor."""

    address: int
    scale: float = 1.0
    signed: bool = False
    words: int = 2
    entity_category: EntityCategory | None = None
    maximum: float | None = None


IDENTIFICATION_CODES: dict[int, str] = {
    270: "EM27072DMV53X2S",
    271: "EM27072DMV53XOS",
    272: "EM27072DMV63X2S",
    273: "EM27072DMV63XOS",
    280: "EM28072DMV53X2SX",
    281: "EM28072DMV53XOSX",
    282: "EM28072DMV63X2SX",
    283: "EM28072DMV63XOSX",
}

MEASURING_SYSTEM_OPTIONS = {
    0: "3P 1.3P",
    1: "3P 2.3P",
    2: "3P 3.1P",
    3: "3P 6.1P",
    4: "1P 3.1P",
    5: "1P 6.1P",
}
CT_PRIMARY_EM270 = {
    0: "160 A",
    1: "250 A",
    2: "630 A",
    3: "65 A / no TCD detected (model dependent)",
    4: "No TCD detected",
}
CT_PRIMARY_EM280 = {0: "TCD06B", 1: "TCD06S", 4: "No TCD detected"}
SUM_VIRTUAL_EM270 = {
    0: "Disabled / virtual disabled",
    1: "SUM enabled",
    2: "DIF enabled",
}
SUM_MODE_OPTIONS = {0: "Disabled", 1: "Enabled"}
TON_TIME_OPTIONS = {0: "40 ms", 1: "100 ms"}
EC_MODE_OPTIONS = {0: "Enabled", 1: "Disabled"}
PHASE_ORDER_OPTIONS = {0: "123", 1: "321"}
RS485_BAUD_OPTIONS = {0: "9600", 1: "19200", 2: "38400"}
RS485_PARITY_OPTIONS = {0: "None", 1: "Even"}
LOCK_STATUS_OPTIONS = {0: "Unlocked", 1: "Locked"}


SENSOR_DESCRIPTIONS: tuple[RegisterSensorDescription, ...] = (
    RegisterSensorDescription(
        key="v_l1_n",
        name="V L1-N",
        address=0x0000,
        scale=10,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        maximum=5000,
    ),
    RegisterSensorDescription(
        key="v_l2_n",
        name="V L2-N",
        address=0x0002,
        scale=10,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        maximum=5000,
    ),
    RegisterSensorDescription(
        key="v_l3_n",
        name="V L3-N",
        address=0x0004,
        scale=10,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        maximum=5000,
    ),
    RegisterSensorDescription(
        key="v_l1_l2",
        name="V L1-L2",
        address=0x0006,
        scale=10,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        maximum=5000,
    ),
    RegisterSensorDescription(
        key="v_l2_l3",
        name="V L2-L3",
        address=0x0008,
        scale=10,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        maximum=5000,
    ),
    RegisterSensorDescription(
        key="v_l3_l1",
        name="V L3-L1",
        address=0x000A,
        scale=10,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        maximum=5000,
    ),
    RegisterSensorDescription(
        key="a_l1_sum",
        name="A L1 Σ",
        address=0x000C,
        scale=1000,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="a_l2_sum",
        name="A L2 Σ",
        address=0x000E,
        scale=1000,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="a_l3_sum",
        name="A L3 Σ",
        address=0x0010,
        scale=1000,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="w_sum",
        name="W Σ",
        address=0x0012,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="va_sum",
        name="VA Σ",
        address=0x0014,
        scale=10,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="var_sum",
        name="VAR Σ",
        address=0x0016,
        scale=10,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="kwh_import_total",
        name="kWh Import Total",
        address=0x0018,
        scale=10,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    RegisterSensorDescription(
        key="kvarh_import_total",
        name="kvarh Import Total",
        address=0x001A,
        scale=10,
        native_unit_of_measurement=(
            UnitOfReactiveEnergy.KILO_VOLT_AMPERE_REACTIVE_HOUR
        ),
        device_class=SensorDeviceClass.REACTIVE_ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    RegisterSensorDescription(
        key="w_dmd_sum",
        name="W DMD Σ",
        address=0x001C,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="va_dmd_sum",
        name="VA DMD Σ",
        address=0x001E,
        scale=10,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="w_maxdmd_sum",
        name="W MAXDMD Σ",
        address=0x0020,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="va_maxdmd_sum",
        name="VA MAXDMD Σ",
        address=0x0022,
        scale=10,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="pf_sum",
        name="PF Σ",
        address=0x0024,
        scale=1000,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_a_l1",
        name="TCDA1 A L1",
        address=0x010C,
        scale=1000,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="tcda1_a_l2",
        name="TCDA1 A L2",
        address=0x010E,
        scale=1000,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="tcda1_a_l3",
        name="TCDA1 A L3",
        address=0x0110,
        scale=1000,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="tcda1_w_l1",
        name="TCDA1 W L1",
        address=0x0112,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_w_l2",
        name="TCDA1 W L2",
        address=0x0114,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_w_l3",
        name="TCDA1 W L3",
        address=0x0116,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_w_total",
        name="TCDA1 W Total",
        address=0x0118,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_va_total",
        name="TCDA1 VA Total",
        address=0x011A,
        scale=10,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="tcda1_var_total",
        name="TCDA1 VAR Total",
        address=0x011C,
        scale=10,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_kwh_total",
        name="TCDA1 kWh Total",
        address=0x011E,
        scale=10,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    RegisterSensorDescription(
        key="tcda1_kvarh_total",
        name="TCDA1 kvarh Total",
        address=0x0120,
        scale=10,
        native_unit_of_measurement=(
            UnitOfReactiveEnergy.KILO_VOLT_AMPERE_REACTIVE_HOUR
        ),
        device_class=SensorDeviceClass.REACTIVE_ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    RegisterSensorDescription(
        key="tcda1_w_dmd_total",
        name="TCDA1 W DMD Total",
        address=0x0122,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_va_dmd_total",
        name="TCDA1 VA DMD Total",
        address=0x0124,
        scale=10,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="tcda1_w_maxdmd_total",
        name="TCDA1 W MAXDMD Total",
        address=0x0126,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_va_maxdmd_total",
        name="TCDA1 VA MAXDMD Total",
        address=0x0128,
        scale=10,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="tcda1_kwh_l1",
        name="TCDA1 kWh L1",
        address=0x012A,
        scale=10,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    RegisterSensorDescription(
        key="tcda1_kwh_l2",
        name="TCDA1 kWh L2",
        address=0x012C,
        scale=10,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    RegisterSensorDescription(
        key="tcda1_kwh_l3",
        name="TCDA1 kWh L3",
        address=0x012E,
        scale=10,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    RegisterSensorDescription(
        key="tcda1_w_dmd_l1",
        name="TCDA1 W DMD L1",
        address=0x0130,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_w_dmd_l2",
        name="TCDA1 W DMD L2",
        address=0x0132,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_w_dmd_l3",
        name="TCDA1 W DMD L3",
        address=0x0134,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_w_maxdmd_l1",
        name="TCDA1 W MAXDMD L1",
        address=0x0136,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_w_maxdmd_l2",
        name="TCDA1 W MAXDMD L2",
        address=0x0138,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_w_maxdmd_l3",
        name="TCDA1 W MAXDMD L3",
        address=0x013A,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_var_l1",
        name="TCDA1 VAR L1",
        address=0x013C,
        scale=10,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_var_l2",
        name="TCDA1 VAR L2",
        address=0x013E,
        scale=10,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_var_l3",
        name="TCDA1 VAR L3",
        address=0x0140,
        scale=10,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_pf_l1",
        name="TCDA1 PF L1",
        address=0x0142,
        scale=1000,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_pf_l2",
        name="TCDA1 PF L2",
        address=0x0144,
        scale=1000,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_pf_l3",
        name="TCDA1 PF L3",
        address=0x0146,
        scale=1000,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda1_pf_total",
        name="TCDA1 PF Total",
        address=0x0148,
        scale=1000,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_a_l1",
        name="TCDA2 A L1",
        address=0x020C,
        scale=1000,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="tcda2_a_l2",
        name="TCDA2 A L2",
        address=0x020E,
        scale=1000,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="tcda2_a_l3",
        name="TCDA2 A L3",
        address=0x0210,
        scale=1000,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="tcda2_w_l1",
        name="TCDA2 W L1",
        address=0x0212,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_w_l2",
        name="TCDA2 W L2",
        address=0x0214,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_w_l3",
        name="TCDA2 W L3",
        address=0x0216,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_w_total",
        name="TCDA2 W Total",
        address=0x0218,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_va_total",
        name="TCDA2 VA Total",
        address=0x021A,
        scale=10,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="tcda2_var_total",
        name="TCDA2 VAR Total",
        address=0x021C,
        scale=10,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_kwh_total",
        name="TCDA2 kWh Total",
        address=0x021E,
        scale=10,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    RegisterSensorDescription(
        key="tcda2_kvarh_total",
        name="TCDA2 kvarh Total",
        address=0x0220,
        scale=10,
        native_unit_of_measurement=(
            UnitOfReactiveEnergy.KILO_VOLT_AMPERE_REACTIVE_HOUR
        ),
        device_class=SensorDeviceClass.REACTIVE_ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    RegisterSensorDescription(
        key="tcda2_w_dmd_total",
        name="TCDA2 W DMD Total",
        address=0x0222,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_va_dmd_total",
        name="TCDA2 VA DMD Total",
        address=0x0224,
        scale=10,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="tcda2_w_maxdmd_total",
        name="TCDA2 W MAXDMD Total",
        address=0x0226,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_va_maxdmd_total",
        name="TCDA2 VA MAXDMD Total",
        address=0x0228,
        scale=10,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        device_class=SensorDeviceClass.APPARENT_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    RegisterSensorDescription(
        key="tcda2_kwh_l1",
        name="TCDA2 kWh L1",
        address=0x022A,
        scale=10,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    RegisterSensorDescription(
        key="tcda2_kwh_l2",
        name="TCDA2 kWh L2",
        address=0x022C,
        scale=10,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    RegisterSensorDescription(
        key="tcda2_kwh_l3",
        name="TCDA2 kWh L3",
        address=0x022E,
        scale=10,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    RegisterSensorDescription(
        key="tcda2_w_dmd_l1",
        name="TCDA2 W DMD L1",
        address=0x0230,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_w_dmd_l2",
        name="TCDA2 W DMD L2",
        address=0x0232,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_w_dmd_l3",
        name="TCDA2 W DMD L3",
        address=0x0234,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_w_maxdmd_l1",
        name="TCDA2 W MAXDMD L1",
        address=0x0236,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_w_maxdmd_l2",
        name="TCDA2 W MAXDMD L2",
        address=0x0238,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_w_maxdmd_l3",
        name="TCDA2 W MAXDMD L3",
        address=0x023A,
        scale=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_var_l1",
        name="TCDA2 VAR L1",
        address=0x023C,
        scale=10,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_var_l2",
        name="TCDA2 VAR L2",
        address=0x023E,
        scale=10,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_var_l3",
        name="TCDA2 VAR L3",
        address=0x0240,
        scale=10,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_pf_l1",
        name="TCDA2 PF L1",
        address=0x0242,
        scale=1000,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_pf_l2",
        name="TCDA2 PF L2",
        address=0x0244,
        scale=1000,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_pf_l3",
        name="TCDA2 PF L3",
        address=0x0246,
        scale=1000,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="tcda2_pf_total",
        name="TCDA2 PF Total",
        address=0x0248,
        scale=1000,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        signed=True,
    ),
    RegisterSensorDescription(
        key="measuring_system",
        name="Measuring System",
        address=MEASURING_SYSTEM_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="ct_primary",
        name="CT Primary",
        address=CT_PRIMARY_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="ct_primary_2",
        name="CT Primary 2",
        address=CT_PRIMARY_2_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="vt_ratio",
        name="VT Ratio",
        address=VT_RATIO_ADDRESS,
        words=1,
        scale=10,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="sum_virtual",
        name="SUM / Virtual",
        address=SUM_VIRTUAL_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="dmd_integration_time",
        name="DMD Integration Time",
        address=DMD_INTEGRATION_ADDRESS,
        words=1,
        native_unit_of_measurement="min",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="ton_time",
        name="Ton Time",
        address=TON_TIME_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="kwh_per_pulse_out1",
        name="kWh per Pulse OUT1",
        address=KWH_PER_PULSE_OUT1_ADDRESS,
        words=1,
        scale=100,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="kwh_per_pulse_out2",
        name="kWh per Pulse OUT2",
        address=KWH_PER_PULSE_OUT2_ADDRESS,
        words=1,
        scale=100,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="ec_mode",
        name="Easy Connection",
        address=EC_MODE_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="tcd_phase_order_a1",
        name="TCD Phase Order A1",
        address=TCD_PHASE_ORDER_A1_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="tcd_phase_order_a2",
        name="TCD Phase Order A2",
        address=TCD_PHASE_ORDER_A2_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="rs485_address",
        name="RS485 Address",
        address=RS485_ADDRESS_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="rs485_baud",
        name="RS485 Baud",
        address=RS485_BAUD_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="rs485_parity",
        name="RS485 Parity",
        address=RS485_PARITY_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="keypad_lock",
        name="Keypad Lock",
        address=LOCK_STATUS_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="production_year",
        name="Production year",
        address=PRODUCTION_YEAR_ADDRESS,
        words=1,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    RegisterSensorDescription(
        key="secondary_address",
        name="Secondary address",
        address=SECONDARY_ADDRESS_START,
        words=2,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
)


def map_option(
    description: RegisterSensorDescription,
    raw: int,
    model_family: str,
) -> str | int:
    """Map a numeric configuration value to a human-readable state."""
    if description.key == "measuring_system":
        return MEASURING_SYSTEM_OPTIONS.get(raw, raw)
    if description.key in {"ct_primary", "ct_primary_2"}:
        mapping = CT_PRIMARY_EM280 if model_family == "em280" else CT_PRIMARY_EM270
        return mapping.get(raw, raw)
    if description.key == "sum_virtual":
        mapping = SUM_MODE_OPTIONS if model_family == "em280" else SUM_VIRTUAL_EM270
        return mapping.get(raw, raw)
    if description.key == "ton_time":
        return TON_TIME_OPTIONS.get(raw, raw)
    if description.key == "ec_mode":
        return EC_MODE_OPTIONS.get(raw, raw)
    if description.key in {"tcd_phase_order_a1", "tcd_phase_order_a2"}:
        return PHASE_ORDER_OPTIONS.get(raw, raw)
    if description.key == "rs485_baud":
        return RS485_BAUD_OPTIONS.get(raw, raw)
    if description.key == "rs485_parity":
        return RS485_PARITY_OPTIONS.get(raw, raw)
    if description.key == "keypad_lock":
        return LOCK_STATUS_OPTIONS.get(raw, raw)
    return raw
